### DISCUSSION TITLE
How to update a docker container to run latest code

### DISCUSSION THREAD

**Discussion by adanielyan** [tolgee/tolgee-platform#1467] [Q&A] [answered]
Hi, I have a deployment of tolgee in a docker container. I wonder what's the right way to update the version of tolgee within that container. Please help!

**Comment by JanCizmar** [comment, marked as answer]
Hey, you have to remove the old container and run a new one with the new image version. You have to mount the volume from deleted container to the new one.

**Comment by adanielyan** [comment]
Doing it removed all of my data including user accounts... Fortunately it was only test data, but I don't see how this can work in production.

**Reply by JanCizmar** [reply]
What was the command you used to start the container?

**Reply by adanielyan** [reply]
I used docker-compose configuration:
```yaml
version: '3'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
  app:
    image: tolgee/tolgee
    volumes:
     - ./data:/data
    ports:
      - "8899:8080"
    env_file:
      - .env
    depends_on:
      - "db"
```

and this is my .env
```ini
JAVA_OPTS="-Xms128m -Xmx1024m"

spring_datasource_url=jdbc:postgresql://db:5432/postgres
spring_datasource_username=postgres
spring_datasource_password=postgres
tolgee_postgres_autostart_enabled=false
tolgee_authentication_enabled=true
tolgee_authentication_create_nitial_user=true
tolgee_authentication_initial_username=admin
tolgee_authentication_user_can_create_organizations=false
tolgee_front_end_url=https://tolgee.example.com
tolgee_max_upload_file_size=10240
tolgee_smtp_host=smtp.example.com
tolgee_smtp_username=<username>
tolgee_smtp_password=<password>
tolgee_smtp_port=587
tolgee_smtp_auth=true
tolgee_smtp_tls_enabled=true
tolgee_smtp_from=Tolgee no-reply <tolgee@example.com>
```
