### DISCUSSION TITLE
Copy database from old instance

### DISCUSSION THREAD

**Discussion by piotrszpruta** [tolgee/tolgee-platform#1847] [General]
Hello,
I've moved to different system and I would like to copy database from old tolgee and docker setup I had. I have access to just files from that machine and I can't find any help to do that. Please could you provide me with some examples how I could achieve that?

**Comment by JanCizmar** [comment]
Hello! We cannot help you with this unless you provide more detailed information about your deployment. Do you use Docker compose? How does your `docker-compose.yaml` looks like?

**Reply by piotrszpruta** [reply]
Yes I've used docker compose. That's how it looks:

```
version: '3'

services:
  app:
    image: tolgee/tolgee
    volumes:
      - ./data:/data
      - ./config.yaml:/config.yaml
    ports:
      - "25432:25432" # if you would like to access the DB
      - "8080:8080"
    environment:
      spring.config.additional-location: file:///config.yaml
```
