### DISCUSSION TITLE
How to use Azure SQL Server Database as datasource

### DISCUSSION THREAD

**Discussion by AntonioSCoelho** [tolgee/tolgee-platform#1955] [Q&A] [answered]
Hi All,

Is it possible to use an Azure SQL Server Database as [datasource](https://tolgee.io/platform/self_hosting/configuration?config-format=properties#data-source-settings)? 

I've tried to change the .env settings to something like this:

```
tolgee.postgres-autostart.enabled=false

spring.datasource.url=jdbc:sqlserver://my_server.database.windows.net:1433;database=tolgee;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=user
spring.datasource.password=my_pass
```

When running the docket, I get the following error:
`Failed to load driver class com.microsoft.sqlserver.jdbc.SQLServerDriver from HikariConfig class classloader jdk.internal.loader.ClassLoaders`

My _docker-compose.yml_ looks like this:
```
version: '3'

services:
  app:
    image: tolgee/tolgee
    ports:
      - ${exposePort}:8080
    env_file:
      - .env

```
