### DISCUSSION TITLE
Deployment on Google Cloud Platform

### DISCUSSION THREAD

**Discussion by ehundt** [tolgee/tolgee-platform#2892] [Q&A] [answered]
Hi there,

I was trying to deploy the Tolgee Docker image as a Cloud Run instance on Google Cloud Platform with a Postgres database in Cloud SQL.

[Here](https://martinelli.ch/connect-to-google-cloud-sql-from-java/) I found that I should set 
```
spring.datasource.url = jdbc:postgresql:///<DATABASE>?cloudSqlInstance=<INSTANCE_NAME>&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=<USER>&password=<PASSWORD>
```

It seems that I would need the dependency com.google.cloud.sql.postgres.SocketFactory installed.

Are there any solutions how I can proceed?

**Comment by JanCizmar** [comment]
Hey! You can submit PR adding such dependency to Tolgee's data module.

Do you have any idea why google doesn't work with standard Postgre's configuration?

**Reply by ehundt** [reply]
Hi Jan, 
thanks for your answer :-) I am actually not sure whether I just did something wrong. I am not a Java developer...

**Reply by JanCizmar** [reply]
So does it work now?

**Comment by Beleren** [comment, marked as answer]
What I needed to do to make it work:

1. Cloud SQL proxy as a sidecar container (not the built-in connector) to provide TCP on 127.0.0.1:5432
2. gen2 execution environment for GCS FUSE support
3. Container dependency ordering: Tolgee waits for the proxy to be ready before starting
4. Extended startup probes for both the proxy and the Java app

What didn't work — Built-in Cloud SQL connector

# Single container with Cloud SQL annotation
```
metadata:
  annotations:
    run.googleapis.com/cloudsql-instances: my-project:us-central1:my-db-instance
spec:
  containers:
  - name: tolgee-1
    env:
    - name: SPRING_DATASOURCE_URL
      # This fails — nothing listens on TCP 5432
      value: jdbc:postgresql://localhost:5432/tolgee
    image: tolgee/tolgee:latest
```
The annotation creates a Unix socket at /cloudsql/my-project:us-central1:my-db-instance/.s.PGSQL.5432, but JDBC can't use Unix sockets.

What works — Cloud SQL Proxy sidecar

# Multi-container: Tolgee + cloud-sql-proxy sidecar
```
metadata:
  annotations:
    # Ensure proxy starts BEFORE Tolgee
    run.googleapis.com/container-dependencies: '{"tolgee-1":["cloud-sql-proxy"]}'
spec:
  containers:
  - name: tolgee-1
    env:
    - name: SPRING_DATASOURCE_URL
      # Works — proxy listens on TCP 127.0.0.1:5432
      value: jdbc:postgresql://127.0.0.1:5432/tolgee
    image: tolgee/tolgee:latest
    # ... rest of tolgee config
```
  # Sidecar container that provides TCP proxy
```
  - name: cloud-sql-proxy
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.3
    args:
    - my-project:us-central1:my-db-instance
    - --address=0.0.0.0
    - --port=5432
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
    startupProbe:
      tcpSocket:
        port: 5432
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 30
      timeoutSeconds: 3
```
The key differences:

1. Removed the run.googleapis.com/cloudsql-instances annotation
2. Added a cloud-sql-proxy sidecar container that listens on 0.0.0.0:5432 (TCP)
3. Added container dependency so the proxy starts first
4. Added a startup probe on the proxy so Tolgee waits until it's ready
5. JDBC URL uses 127.0.0.1:5432 which hits the proxy's TCP listener
