### ISSUE TITLE
No dashes in environmental variables

### ISSUE THREAD

**Issue by vascYT** [tolgee/tolgee-platform#1321]
Hey, I just started using Tolgee and I love it. Although I just have one problem. I cannot use dashes ("-") in my env variables, so I can't use all env variables from the docs (e.g. ``tolgee.postgres-autostart.enabled``).

![W8X2bIOdPnDF8en](https://user-images.githubusercontent.com/39592306/186061823-68eeecc9-9058-4b6a-82bc-e7094f7e4f3d.png)

Here is my docker compose version:
![cTYfhtCHCqAcc50](https://user-images.githubusercontent.com/39592306/186061944-236ca8a7-74f0-4daf-9687-8ded27878340.png)

**Comment by JanCizmar** [comment]
Replace dashes with underscores or use camelCase. Can you please also share you docker-compose.yaml file?

**Comment by vascYT** [comment]
So I tried to use ``tolgee.postgresAutostart.enabled`` and it seems to work, thanks.

Although I cannot use ``user-can-create-projects`` and ``user-can-create-organizations`` with camel case (``userCanCreateProjects`` & ``userCanCreateOrganizations``). I also tried using underscores.

**Comment by JanCizmar** [comment]
Hope it will work. Otherwise you set  
```
spring_config_location=/application.properties
```
and then mount the file as a volume.

Property files support both `.` and `-`.

**Comment by vascYT** [comment]
Do I then put all my env variables in the property file?

**Comment by JanCizmar** [comment]
You can.

**Comment by vascYT** [comment]
Okay perfect. I'll try this then.

**Comment by vascYT** [comment]
Now I get an error when starting the container:
[tolgee-app-1_logs.txt](https://github.com/tolgee/tolgee-platform/files/9404447/_tolgee-app-1_logs.txt)

docker-compose.yml
```yaml
version: "3"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=xxx
    volumes:
      - tolgee_db:/var/lib/postgresql/data
  app:
    image: tolgee/tolgee
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tolgee.rule=Host(`xxx.xxx.xxx`)"
      - "traefik.http.routers.tolgee.entrypoints=web"
      - "traefik.http.services.tolgee.loadbalancer.server.port=8080"
    volumes:
     - ./data:/data
     - ./application.properties:/application.properties
    expose:
    - "8080"
    env_file:
      - .env
    depends_on:
      - "db"
volumes:
  tolgee_db:
```
and .env file:
```env
spring_config_location=/application.properties
```
and the application.properties is correctly mounted as you can see here (console from inside the container):
![image](https://user-images.githubusercontent.com/39592306/186212228-cf4d729d-f430-472a-ad98-7c2b3a30f388.png)
