### ISSUE TITLE
YAML Import & Export support

### ISSUE THREAD

**Issue by Crovitche-1623** [tolgee/tolgee-platform#1591]
Hi !

I plan to switch from Lokalise to Tolgee because I need a self-hosted solution for my project containing hundreds of thousands of translations. There is a crucial feature for me that is missing which is import and export in YAML. Are you planning to support this format (which is basically the same as flat JSON) or what would be missing in order to have it?

Here is an example of one of my YAML translation file:

`[namespace].[language].yml` : `shape.fr.yml`

```yaml
shape.oval: Ovale
shape.rectangular: Rectangulaire
shape.round: Rond
shape.square: Carré
shape.tonneau: Tonneau
```

**Comment by JanCizmar** [comment]
Hey! It's not complicated. However it's not a priority

@Crovitche-1623 I've pinged you via e-mail, about our EE plan for self-hosted instances, you might be interested to. It comes with prioritised feature implementation.

**Comment by stijnb1234** [comment]
+1, it would be great if nested YAML would work too:
```yaml
shape:
  oval: Ovale
  rectangular: Rectangulaire
```
