### ISSUE TITLE
Receiving a error when trying to view projects

### ISSUE THREAD

**Issue by NgLoader** [tolgee/tolgee-platform#1690]
Hey, I just created a new project and after refreshing my page this error appears.
I just created a brand new docker image and just change the admin username and email to mine.
After that I created a new project and added an api key for my angular application.

## Error
Message: `Character I is neither a decimal digit number, decimal point, nor "e" notation exponential mark.`
Full log: https://gist.github.com/NgLoader/a8f8dc91ee3dc7efa59306e4cc9dcff1

## Config
<details>
  <summary>Docker compose</summary>

  ```
  version: '3'
  
  services:
    app:
      image: tolgee/tolgee
      restart: always
      volumes:
       - ./data:/data
      env_file:
        - .env
  ```
</details>

<details>
  <summary>.env</summary>

  ```
########## TOLGEE ##############
tolgee.postgres-autostart.enabled=true
tolgee.authentication.enabled=true
tolgee.authentication.needs-email-verification=true

########## SMTP ##############
tolgee.smtp.host=smtp.****.com
tolgee.smtp.username=****@****.com
tolgee.smtp.password=****
tolgee.smtp.port=465
tolgee.smtp.auth=true
tolgee.smtp.ssl-enabled=true
tolgee.smtp.from=no-reply@****.eu
  ```
</details>

![image](https://user-images.githubusercontent.com/13753840/235311059-4d5eccd9-8b08-4b67-9b8c-e39368c0b7eb.png)
