### ISSUE TITLE
Hard time connecting with socket.io

### ISSUE THREAD

**Issue by daviderenger** [tolgee/tolgee-platform#1708]
Hi,

I'm struggling a bit here getting socket.io to connect to my docker instance of tolgee.

So I'm running tolgee in a docker container, it uses a config file like this:

```
tolgee:
  rate-limiter:
    enabled: false
  apiKey: 'verySecret'
  authentication:
    enabled: false
    user-can-create-organizations: false
  socket-io:
    enabled: true
    host: 0.0.0.0
    external-url: http://tolgee:9090
    port: 9090
    allowed-transports[0]: websocket
    allowed-transports[1]: polling
```

    
    
The service name is tolgee so I can call the API from another service in the swarm like this:

http://tolgee:8080/v2/projects/23/whateverEndpoint

with my APIkey as header: 

```
headers: {
    'Content-Type': 'application/json',
    'X-API-Key': `${API_KEY}`,
  },
```
  
  But I'm not able to connect with socket.io at all. I have tried with a thousand different endpoints with no luck. The most logical one being:
  
  ```
  const TOLGEE_SOCKETIO_URL = 'http://tolgee:9090/';
  const socket = io(
    TOLGEE_SOCKETIO_URL,
    {
      query: {
        ak: API_KEY,
      },
    }
  );
```
  
  But all I'm getting is ECONNREFUSED 172.XX.X.107:9090 whatever I try.
  
  I'm I missing something here, what should the endpoint be and is it possible to see in the server logs that it actually started up the socket.io client?
