### ISSUE TITLE
Error after deleting LocalStorage: crypto.randomUUID is not a function 

### ISSUE THREAD

**Issue by EnCz** [tolgee/tolgee-platform#1848]
After emptying localstorage I can't open the site any more ( it stays white ).

Inside developer console it says "crypto.randomUUID is not a function":
![image](https://github.com/tolgee/tolgee-platform/assets/7642122/0e7bb6b0-3011-4fa6-8e6a-84a45e221543)

After manually adding "anonymousUserId" into my localStorage ( with some random value ) the page starts working again.

This is reproduceable even in an anonymous browser, it simply stays white.

I use it via docker:

```
version: '3'

services:
  app:
    image: tolgee/tolgee:latest
    volumes:
      - ./volumes/tolgee/data:/data
      - ./volumes/tolgee/config.yml:/config.yml
    ports:
      - "80:8080"
    environment:
      spring.config.additional-location: file:///config.yml
```

config.yml:
```
tolgee:
  authentication:
    enabled: true
    initial-password: _censored_
    initial-username: _censored_
    jwt-secret: _censored_

```

any idea how to work around this problem ?
