### ISSUE TITLE
initial credentials do not work

### ISSUE THREAD

**Issue by cxnky** [tolgee/tolgee-platform#1878]
i'm trying to set this up on docker and i'm following the documentation, but when i try and specify

```yaml
tolgee:
  authentication:
      initial-password: admin
      initial-username: admin
```

and i try and log into the UI using those details, it just says "Invalid credentials". then it also says that the admin password will be generated and stored under ``/data/initial.pwd`` in the container, but there's nothing there.

```
bash-5.1# cd data
bash-5.1# ls -arilh
total 12K    
 271091 drwx------   19 postgres root        4.0K Aug 27 19:37 postgres
 269922 drwxr-xr-x    1 root     root        4.0K Aug 27 19:36 ..
 271076 drwxr-xr-x    3 root     root        4.0K Aug 27 19:20 .
bash-5.1# 
```

also, the use of initial-username in the docs, and then asking me for an email is incredibly confusing.
