### ISSUE TITLE
Unexpected behaviour TOLGEE_AUTHENTICATION_NATIVE_ENABLED=false  with TOLGEE_AUTHENTICATION_REGISTRATIONS_ALLOWED=true

### ISSUE THREAD

**Issue by Megamannen** [tolgee/tolgee-platform#1944]
A bit unsure on if this is really a fault or by design

But my aim was:
* Only google auth login
* No registration

First tried 
```env
TOLGEE_AUTHENTICATION_REGISTRATIONS_ALLOWED=false
TOLGEE_AUTHENTICATION_GOOGLE_CLIENT_ID=....
TOLGEE_AUTHENTICATION_GOOGLE_CLIENT_SECRET=....
TOLGEE_AUTHENTICATION_GOOGLE_WORKSPACE_DOMAIN=....
```
Then I couldn't login with users that hadn't logged in before. That was not what I expected, but I can understand the logic behind it.

So I activated registrations and disabled native. In my mind that would disable the native registration fields. That wasn't the case and I could register new users with it.
```env
TOLGEE_AUTHENTICATION_REGISTRATIONS_ALLOWED=false
TOLGEE_AUTHENTICATION_NATIVE_ENABLED=false
TOLGEE_AUTHENTICATION_GOOGLE_CLIENT_ID=....
TOLGEE_AUTHENTICATION_GOOGLE_CLIENT_SECRET=....
TOLGEE_AUTHENTICATION_GOOGLE_WORKSPACE_DOMAIN=....
```

The compose I run

```yaml
version: '3'

services:
  tolgee:
    env_file: .env
    image: tolgee/tolgee
    volumes:
      - tolgee-data:/data
    ports:
      - '8080:8080'

volumes:
  tolgee-data:
```

Native registration here
![image](https://github.com/tolgee/tolgee-platform/assets/19424456/b415cc7b-8b03-40fa-bc8b-2ee51c9f3d19)
