### ISSUE TITLE
Tolgee not able to connect to postgresql in docker container

### ISSUE THREAD

**Issue by targetingsnake** [tolgee/tolgee-platform#2100]
Hey guys, 

since one of the recent updates tolgee isn't able to connect to the internal postgresql database. We currently run into the issue seen in the attached log: [tolgee-log.txt](https://github.com/tolgee/tolgee-platform/files/13998422/tolgee-log.txt)

With Kind Regards
Targetingsnake / Antistasi Dev-Team

**Comment by targetingsnake** [comment]
We use the following config:

```
tolgee:
  authentication:
    initial-password: $Initial_Password$
    initial-username: $Initial_Username$
    enabled: true
  machine-translation:
    google:
      api-key: my_google_api_key
  smtp:
    auth: false
    from: Antistasi Translate <$Sender_Mail$>
    host: $Mailserver_IP$
    password: 'omg/my/password'
    port: 25
    ssl-enabled: false
    username: $Sender_Mail$
  rate-limits:
    enabled: false
```

in which these parameters are actually replaced with the depending values:

- `$Initial_Password$`
- `$Initial_Username$`
- `$Sender_Mail$`
- `$Sender_Mail$`

all other values are like in the code block above

**Comment by targetingsnake** [comment]
Our docker compose file is the following:

```
version: '7'

services:
  app:
    image: tolgee/tolgee:latest
    volumes:
      - ./data:/data
      - ./config.yaml:/config.yaml # <--- this line
    ports:
      - '25432:25432'
      - '8080:8080'
    environment:
      spring.config.additional-location: file:///config.yaml # <--- this line
```
