### ISSUE TITLE
"Not found" when trying to edit translation for locale

### ISSUE THREAD

**Issue by dammitt** [tolgee/tolgee-platform#2148]
Okay, this is a pretty weird one. 

There are like 2500 keys in project and everything worked great, until I moved the database to a new server. Translators started reporting strange issue when trying to add translation to certain keys - they input some text, hit Enter and then "Not found" notification appears at the bottom left corner. 

In this case `/v2/projects/1/translations` returns 404 with the following response: 

```
{"code":"key_not_found","params":null}
```

I have no idea what could be causing these. All keys were added in bulk for all languages present in the project. All languages were added just once. 
And there's no pattern at all:
1. Translation for key A can be added/updated for any language without any problem
2. Translation for key B can be added/update for 6/8 languages (including base one, English), and the other 2/8 return 404. 
3. Translation for key C can be added/update for 4/8 languages (including base one, English), and the other 4/8 return 404. And compared to key B the languages that have the problem could be completely different.

I'm using the latest version of Tolgee, running it [with external PostgreSQL db](https://tolgee.io/platform/self_hosting/running_with_docker#running-with-docker-compose-with-external-postgresql-database).

**Comment by dammitt** [comment]
Some additional info:

1. I (as admin) can't add translations via web UI to such keys either
2. If you import a file with these problematic key translations, then translations are added correctly and there's no error – this is currently the only workaround, but it requires extra actions from translators :(

**Comment by dammitt** [comment]
Latest version. Just standard setup, no caching (unless there's default caching in there?).

Here are my configs: 

**docker-compose.yml**
```
version: '3'

services:
  app:
    image: tolgee/tolgee:latest
    volumes:
      - ./data:/data
      - ./config.yaml:/config.yaml
    ports:
      - '8085:8080'
    environment:
      spring.config.additional-location: file:///config.yaml 
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - '25432:5432'
```

**config.yaml**
```
tolgee:
  authentication:
    enabled: true
    registrations-allowed: true
    user-can-create-organizations: false
    initial-password: admin
    initial-username: admin
  smtp:
    auth: true
    from: <...>
    host: <...>
    password: <...>
    port: 587
    ssl-enabled: false
    username: <...>
  postgres-autostart:
    enabled: false
spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
```

**Comment by JanCizmar** [comment]
That's weird indeed. There is default in memory caching, but the cache is evicted on the server restart. Have you tried looking into the db if the records are really there? Also, you can try to enable sql logging and try to run the exact queries against the db. 

Add this to the config to see the sql queries.
```
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
```
