### ISSUE TITLE
Machine translation issue

### ISSUE THREAD

**Issue by compi-tom** [tolgee/tolgee-platform#2211]
Hello,

Further testing on our part to see if Tolgee can meet our needs (side note: the workaround mentioned in https://github.com/tolgee/tolgee-platform/issues/2100#issuecomment-1938361876 is working). 

I'm facing a new issue and couldn't find any workaround / possible fix. 
I've set a Google Cloud translate API key and a free Deepl API key in our config.yaml file:
```
tolgee:
  postgres-autostart:
    enabled: false
  authentication:
    enabled: true
    initial-password: <strong_pwd>
    initial-username: <my_user>
    jwt-secret: <super_secret>
  machine-translation:
    deepl:
      api-key: <free_deepl_api_key_ending_with:fx>
      default-enabled: true
      default-primary: false
    google:
      api-key: <google_cloud_translation_api_key>
      default-enabled: true
      default-primary: true
spring:
  datasource:
    url: jdbc:postgresql://<container_name>:5432/<my_db>
    username: <my_user>
    password: <strong_pwd>
```

Issues faced:

1. Only the Google Machine Translation is available (yes, the Deepl API key is right and we were able to test it in another tool)
2. When using the Google Machine Translation, we are getting the below error even if our domain is whitelisted for this API Key:
```
{
  "code" : 403,
  "details" : [ {
    "@type" : "type.googleapis.com/google.rpc.ErrorInfo",
    "reason" : "API_KEY_HTTP_REFERRER_BLOCKED"
  } ],
  "errors" : [ {
    "domain" : "global",
    "message" : "Requests from referer <empty> are blocked.",
    "reason" : "forbidden"
  } ],
  "message" : "Requests from referer <empty> are blocked.",
  "status" : "PERMISSION_DENIED"
```

Any help with these would be highly appreciated.
Thanks!
