### ISSUE TITLE
Trying to disable native authentication with `tolgee.authentication.native-enabled`=`false`  doesn't work

### ISSUE THREAD

**Issue by emericv** [tolgee/tolgee-platform#2281]
I'm trying to disable native authentication with `tolgee.authentication.native-enabled`=`false`

```yaml
tolgee:
  authentication:
    enabled: true
    native-enabled: false
```

But after a restart, the native login form is still here.

![image](https://github.com/tolgee/tolgee-platform/assets/1727636/8954f0f3-e910-4f7f-9ef3-c38b7e06afbb)

Dockerized Tolgee `v3.59.3`
