### ISSUE TITLE
Import from YAML_RUBY handles percent signs (`%`) incorrectly when ICU is enabled

### ISSUE THREAD

**Issue by apauly** [tolgee/tolgee-platform#3026]
**Describe the bug**
When the ICU conversion is active, single `%` signs will be interpreted and escaped or treated as placeholder even when they are not part or a placeholder like `%{variable}`.

**To Reproduce**
1. In a blank new project with ICU conversion enabled, upload the following file `en.yml`:
```
en:
  key_1: "Edit %{model}"
  some_date_fornat: "%a, %d. %B %Y"
  some_unit: "%"
```

2. Visit the translations page and see that "%d" has been treated as a decimal placeholder:

<img width="350" alt="Image" src="https://github.com/user-attachments/assets/ae2d7eb6-dcc8-4d4a-b015-29b20e2b841c" />

3. Download the translations and see additional percent signs:
```
en:
  key_1: "Edit %{model}"
  some_date_fornat: "%%a, %2$d. %%B %%Y"
  some_unit: "%%"
```

**Expected behavior**
Percent signs should only be interpreted when they are part of an actual placeholder, e.g. `%{variable}`.
With the example from above, the downloaded file should look like this:
```
en:
  key_1: "Edit %{model}"
  some_date_fornat: "%a, %d. %B %Y"
  some_unit: "%"
```

**Versions and environment**
- Tolgee Platform version: v3.113.2
- Environment: Using Docker image `tolgee/tolgee:v3.113.2`.

**Additional context**
Only workaround I've found so far is to either disable ICU conversion completely or to move the affected translations to a separate file that is not uploaded to tolgee.
